### ISSUE TITLE
Laravel support

### ISSUE THREAD

**Issue by dmitryuk** [DamienHarper/auditor#138]
I see that the package's goal is to make it universal and possible to write own implementations based on it.

I think we can increase community twice if we will create a package like https://github.com/DamienHarper/auditor-bundle for Laravel.
What do you think? I have some experience on this framework

**Comment by DamienHarper** [comment]
Absolutely, I wish to publish a Laravel integration for `auditor` since its beginning but I've not had enough time to do it yet. Also, I don't have any real (professional) experience with Laravel (and Eloquent obviously) so far.

I think we might break it down to an Eloquent provider for `auditor` and a Laravel package (similarly to `auditor-bundle` which is Symfony specific).
