### ISSUE TITLE
Php preload is broken by two classes in one file

### ISSUE THREAD

**Issue by nietonchique** [DamienHarper/auditor#42]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 1.2.0
| PHP version          | 8.0.9
| Database             | PostgreSQL 12.06

#### Summary

Can't preload already declared class DH\Auditor\Event\AuditEvent in <b>/var/www/wl-core/vendor/damienharper/auditor/src/Event/AuditEvent.php</b> on line <b>44</b>

#### How to reproduce

Enable preload in php.ini (bug 100% reproduces on symfony)

#### Expected behavior

You have no errors about preload. You're perfect.

**Comment by DamienHarper** [comment]
@nietonchique Thanks for the feedback. As of now, I can't do much about this to keep Symfony 3.4 backward compatibility. Next major version of `auditor` and `auditor-bundle` will drop support of Symfony 3.4. The problem should be fixed in the next major release.
I close this issue for now but feel free to reopen if needed once next major is released.
